### ISSUE TITLE
MAC segmentation Fault 

### ISSUE THREAD

**Issue by lquirosd** [RParedesPalacios/Layers#1]
Training segmentation Fault error; Error data on attached file:
[error_001.txt](https://github.com/RParedesPalacios/Layers/files/293027/error_001.txt)

Corpus: MNIST
NET file:
[MNIST_cnn.txt](https://github.com/RParedesPalacios/Layers/files/293035/MNIST_cnn.txt)

**Comment by RParedesPalacios** [comment]
Done
