### ISSUE TITLE
error with Eigen compiling Layers on Mac

### ISSUE THREAD

**Issue by jormansa** [RParedesPalacios/Layers#7]
I get the error "**#error The Eigen/Array header does no longer exist in Eigen3.**"
I think including the Eigen folder in the CXXFLAGS is not a good practice (see example http://eigen.tuxfamily.org/dox/GettingStarted.html).
Instead, include the "Eigen" path in all the .cpp/.h files. For instance, in Layers.cpp (line 5):
--- #include "Dense"
+++ #include "Eigen/Dense"

Making this change in all the files solved the compilation error.

**Comment by RParedesPalacios** [comment]
Thanks!
